### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Rick4254** [mmk0083/fitbit-mp-clock#2]
My medical professional clock face shows only minute ticks around clock circle, not any hour ticks or hour numbers. How do I fix?

**Comment by mike21g** [comment]
I love this face but since I did the upgrade on my Versa this morning I have the same problem. All the marks around the circumference are the same.

**Comment by mmk0083** [comment]
Seeing the same thing. Will try to fix it and publish a new version when it's working again. Sorry for the delay in response - didn't get a notification from GitHub that there were issues open.

**Comment by mike21g** [comment]
Thanks! I love that face... 


Regards 
Mike

**Comment by mmk0083** [comment]
I published an update that should be available now. Tested on my own Versa and the clock face looks normal again. Hopefully this works for you as well.

**Comment by mike21g** [comment]
It works! Thank you.
Regards,
Mike
Sent from my Pixel phone
Apologies for typos and brevity
Sent from Blue 
On Sep 7, 2020, at 07:25, mmk0083 <notifications@github.com> wrote:

I published an update that should be available now. Tested on my own Versa and the clock face looks normal again. Hopefully this works for you as well.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/mmk0083/fitbit-mp-clock/issues/2#issuecomment-688262341",
"url": "https://github.com/mmk0083/fitbit-mp-clock/issues/2#issuecomment-688262341",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
